/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.playcontrol.logger;

public interface LoggerConstants {
  public final static String LOGGER_LOGENDTOKEN = LoggerJNI.LOGGER_LOGENDTOKEN_get();
  public final static int LOGGER_MAJOR_VERSION = LoggerJNI.LOGGER_MAJOR_VERSION_get();
  public final static int LOGGER_MINOR_VERSION = LoggerJNI.LOGGER_MINOR_VERSION_get();
  public final static int LOGGER_PATCH_VERSION = LoggerJNI.LOGGER_PATCH_VERSION_get();
}
