/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.playcontrol.logger;

public class LoggerVersion {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public LoggerVersion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(LoggerVersion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LoggerJNI.delete_LoggerVersion(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMajor(int value) {
    LoggerJNI.LoggerVersion_major_set(swigCPtr, this, value);
  }

  public int getMajor() {
    return LoggerJNI.LoggerVersion_major_get(swigCPtr, this);
  }

  public void setMinor(int value) {
    LoggerJNI.LoggerVersion_minor_set(swigCPtr, this, value);
  }

  public int getMinor() {
    return LoggerJNI.LoggerVersion_minor_get(swigCPtr, this);
  }

  public void setPatch(int value) {
    LoggerJNI.LoggerVersion_patch_set(swigCPtr, this, value);
  }

  public int getPatch() {
    return LoggerJNI.LoggerVersion_patch_get(swigCPtr, this);
  }

  public LoggerVersion() {
    this(LoggerJNI.new_LoggerVersion(), true);
  }

}
