/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.playcontrol.logger;

public class LoggerJNI {
  public final static native String LOGGER_LOGENDTOKEN_get();
  public final static native int LOGGER_MAJOR_VERSION_get();
  public final static native int LOGGER_MINOR_VERSION_get();
  public final static native int LOGGER_PATCH_VERSION_get();
  public final static native void LoggerVersion_major_set(long jarg1, LoggerVersion jarg1_, int jarg2);
  public final static native int LoggerVersion_major_get(long jarg1, LoggerVersion jarg1_);
  public final static native void LoggerVersion_minor_set(long jarg1, LoggerVersion jarg1_, int jarg2);
  public final static native int LoggerVersion_minor_get(long jarg1, LoggerVersion jarg1_);
  public final static native void LoggerVersion_patch_set(long jarg1, LoggerVersion jarg1_, int jarg2);
  public final static native int LoggerVersion_patch_get(long jarg1, LoggerVersion jarg1_);
  public final static native long new_LoggerVersion();
  public final static native void delete_LoggerVersion(long jarg1);
  public final static native void GetLinkedVersion(long jarg1, LoggerVersion jarg1_);
  public final static native int IsCompiledWithLocking();
  public final static native void delete_CLogger(long jarg1);
  public final static native long Create();
  public final static native long CreateWithName(String jarg1);
  public final static native void Free(long jarg1, CLogger jarg1_);
  public final static native int LogEventNoFormat(long jarg1, CLogger jarg1_, long jarg2, String jarg3, String jarg4, String jarg5);
  public final static native void Enable(long jarg1, CLogger jarg1_);
  public final static native void Disable(long jarg1, CLogger jarg1_);
  public final static native int IsEnabled(long jarg1, CLogger jarg1_);
  public final static native int Flush(long jarg1, CLogger jarg1_);
  public final static native void EnableAutoFlush(long jarg1, CLogger jarg1_);
  public final static native void DisableAutoFlush(long jarg1, CLogger jarg1_);
  public final static native int IsAutoFlushEnabled(long jarg1, CLogger jarg1_);
  public final static native void SetThresholdPriority(long jarg1, CLogger jarg1_, long jarg2);
  public final static native long GetThresholdPriority(long jarg1, CLogger jarg1_);
  public final static native void SetDefaultPriority(long jarg1, CLogger jarg1_, long jarg2);
  public final static native long GetDefaultPriority(long jarg1, CLogger jarg1_);
  public final static native void SetMinSegmentSize(long jarg1, CLogger jarg1_, long jarg2);
  public final static native long GetMinSegmentSize(long jarg1, CLogger jarg1_);
  public final static native void EchoOn(long jarg1, CLogger jarg1_);
  public final static native void EchoOff(long jarg1, CLogger jarg1_);
  public final static native int IsEchoOn(long jarg1, CLogger jarg1_);
  public final static native void SetEchoToStdout(long jarg1, CLogger jarg1_);
  public final static native void SetEchoToStderr(long jarg1, CLogger jarg1_);
  public final static native void SetPreLines(long jarg1, CLogger jarg1_, long jarg2);
  public final static native void SetPostLines(long jarg1, CLogger jarg1_, long jarg2);
  public final static native void SetNewLines(long jarg1, CLogger jarg1_, long jarg2, long jarg3);
  public final static native long GetPreLines(long jarg1, CLogger jarg1_);
  public final static native long GetPostLines(long jarg1, CLogger jarg1_);
  public final static native int WillLog(long jarg1, CLogger jarg1_, long jarg2);
  public final static native void SetSegmentFormatString(long jarg1, CLogger jarg1_, String jarg2);
  public final static native void Android_SetCustomPrintFunctionToAndroidLog(long jarg1, CLogger jarg1_);
  public final static native void Android_ClearCustomPrintFunctions(long jarg1, CLogger jarg1_);
  public final static native int LogEvent(long jarg1, CLogger jarg1_, long jarg2, String jarg3, String jarg4, String... jarg5);
}
