/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


	#include "Logger.h"
#include "LoggerAdapter__android_log.h"
#include "TimeStamp.h"

SWIGINTERN void delete_Logger(struct Logger *self){
		Logger_Free(self);
    }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jstring JNICALL Java_net_playcontrol_logger_LoggerJNI_LOGGER_1LOGENDTOKEN_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)("\n^@END:$\n");
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_LOGGER_1MAJOR_1VERSION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_LOGGER_1MINOR_1VERSION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_LOGGER_1PATCH_1VERSION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_LoggerVersion_1major_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  LoggerVersion *arg1 = (LoggerVersion *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LoggerVersion **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->major = arg2;
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_LoggerVersion_1major_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  LoggerVersion *arg1 = (LoggerVersion *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LoggerVersion **)&jarg1; 
  result = (int) ((arg1)->major);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_LoggerVersion_1minor_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  LoggerVersion *arg1 = (LoggerVersion *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LoggerVersion **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->minor = arg2;
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_LoggerVersion_1minor_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  LoggerVersion *arg1 = (LoggerVersion *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LoggerVersion **)&jarg1; 
  result = (int) ((arg1)->minor);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_LoggerVersion_1patch_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  LoggerVersion *arg1 = (LoggerVersion *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LoggerVersion **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->patch = arg2;
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_LoggerVersion_1patch_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  LoggerVersion *arg1 = (LoggerVersion *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LoggerVersion **)&jarg1; 
  result = (int) ((arg1)->patch);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_net_playcontrol_logger_LoggerJNI_new_1LoggerVersion(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  LoggerVersion *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (LoggerVersion *)calloc(1, sizeof(LoggerVersion));
  *(LoggerVersion **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_delete_1LoggerVersion(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  LoggerVersion *arg1 = (LoggerVersion *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LoggerVersion **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_GetLinkedVersion(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  LoggerVersion *arg1 = (LoggerVersion *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LoggerVersion **)&jarg1; 
  Logger_GetLinkedVersion(arg1);
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_IsCompiledWithLocking(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)Logger_IsCompiledWithLocking();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_delete_1CLogger(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct Logger *arg1 = (struct Logger *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Logger **)&jarg1; 
  delete_Logger(arg1);
}


SWIGEXPORT jlong JNICALL Java_net_playcontrol_logger_LoggerJNI_Create(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Logger *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Logger *)Logger_Create();
  *(Logger **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_net_playcontrol_logger_LoggerJNI_CreateWithName(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  Logger *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (Logger *)Logger_CreateWithName((char const *)arg1);
  *(Logger **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_Free(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Logger *arg1 = (Logger *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  Logger_Free(arg1);
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_LogEventNoFormat(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jstring jarg3, jstring jarg4, jstring jarg5) {
  jint jresult = 0 ;
  Logger *arg1 = (Logger *) 0 ;
  unsigned int arg2 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  char *arg5 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  arg5 = 0;
  if (jarg5) {
    arg5 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0);
    if (!arg5) return 0;
  }
  result = (int)Logger_LogEventNoFormat(arg1,arg2,(char const *)arg3,(char const *)arg4,(char const *)arg5);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  if (arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, (const char *)arg5);
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_Enable(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Logger *arg1 = (Logger *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  Logger_Enable(arg1);
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_Disable(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Logger *arg1 = (Logger *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  Logger_Disable(arg1);
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_IsEnabled(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Logger *arg1 = (Logger *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  result = (int)Logger_IsEnabled(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_Flush(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Logger *arg1 = (Logger *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  result = (int)Logger_Flush(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_EnableAutoFlush(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Logger *arg1 = (Logger *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  Logger_EnableAutoFlush(arg1);
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_DisableAutoFlush(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Logger *arg1 = (Logger *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  Logger_DisableAutoFlush(arg1);
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_IsAutoFlushEnabled(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Logger *arg1 = (Logger *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  result = (int)Logger_IsAutoFlushEnabled(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_SetThresholdPriority(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Logger *arg1 = (Logger *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  Logger_SetThresholdPriority(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_net_playcontrol_logger_LoggerJNI_GetThresholdPriority(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Logger *arg1 = (Logger *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  result = (unsigned int)Logger_GetThresholdPriority(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_SetDefaultPriority(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Logger *arg1 = (Logger *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  Logger_SetDefaultPriority(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_net_playcontrol_logger_LoggerJNI_GetDefaultPriority(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Logger *arg1 = (Logger *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  result = (unsigned int)Logger_GetDefaultPriority(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_SetMinSegmentSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Logger *arg1 = (Logger *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  Logger_SetMinSegmentSize(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_net_playcontrol_logger_LoggerJNI_GetMinSegmentSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Logger *arg1 = (Logger *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  result = (unsigned int)Logger_GetMinSegmentSize(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_EchoOn(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Logger *arg1 = (Logger *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  Logger_EchoOn(arg1);
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_EchoOff(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Logger *arg1 = (Logger *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  Logger_EchoOff(arg1);
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_IsEchoOn(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Logger *arg1 = (Logger *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  result = (int)Logger_IsEchoOn(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_SetEchoToStdout(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Logger *arg1 = (Logger *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  Logger_SetEchoToStdout(arg1);
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_SetEchoToStderr(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Logger *arg1 = (Logger *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  Logger_SetEchoToStderr(arg1);
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_SetPreLines(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Logger *arg1 = (Logger *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  Logger_SetPreLines(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_SetPostLines(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Logger *arg1 = (Logger *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  Logger_SetPostLines(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_SetNewLines(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  Logger *arg1 = (Logger *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = (unsigned int)jarg3; 
  Logger_SetNewLines(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_net_playcontrol_logger_LoggerJNI_GetPreLines(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Logger *arg1 = (Logger *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  result = (unsigned int)Logger_GetPreLines(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_net_playcontrol_logger_LoggerJNI_GetPostLines(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Logger *arg1 = (Logger *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  result = (unsigned int)Logger_GetPostLines(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_WillLog(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  Logger *arg1 = (Logger *) 0 ;
  unsigned int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (int)Logger_WillLog(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_SetSegmentFormatString(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Logger *arg1 = (Logger *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  Logger_SetSegmentFormatString(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_Android_1SetCustomPrintFunctionToAndroidLog(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Logger *arg1 = (Logger *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  Logger_Android_SetCustomPrintFunctionToAndroidLog(arg1);
}


SWIGEXPORT void JNICALL Java_net_playcontrol_logger_LoggerJNI_Android_1ClearCustomPrintFunctions(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Logger *arg1 = (Logger *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Logger **)&jarg1; 
  Logger_Android_ClearCustomPrintFunctions(arg1);
}



#include "LoggerPrimitives.h"

SWIGEXPORT jint JNICALL Java_net_playcontrol_logger_LoggerJNI_LogEvent(JNIEnv* jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jstring jarg3, jstring jarg4, jobject string_array) {
  jint jresult = 0 ;
  int number_of_strings_in_array;
  int current_stringarray_index;
  	/* logger:LogEvent(pri, "keyword", "subkeyword", "text", "moretext", "moretext") */
  	char time_stamp[LOGGER_TIME_STAMP_SIZE];
	int byte_counter = 0;
	int ret_val;
	int error_flag = 0;
	Logger* logger;
	int priority;
	const char* keyword;
	const char* subkeyword;
	size_t keyword_length = 0;

  (void)jcls;
  (void)jarg1_;

  logger = *(Logger **)&jarg1; 
  priority = (unsigned int)jarg2; 

  /*
  if (jarg5) {
    arg5 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0);
    if (!arg5) return 0;
  }
  */


	LOGGERPRIMITIVES_LOCKMUTEX(logger);

	if(!logger->loggingEnabled)
	{
		LOGGERPRIMITIVES_UNLOCKMUTEX(logger);
		return 0;
	}

	if(0 == priority)
	{
		priority = logger->defaultPriority;
	}
	/* print to log only if priority is >= threshold */
	if(priority < logger->thresholdPriority)
	{
		LOGGERPRIMITIVES_UNLOCKMUTEX(logger);
		return 0;
	}
	
	/* Get the current time */
	TimeStamp_GetTimeStamp(time_stamp, LOGGER_TIME_STAMP_SIZE);

	/* if segmentation is enabled */
	if(logger->minSegmentBytes != 0)
	{
		if(logger->currentByteCount > logger->minSegmentBytes)
		{
			/* SegmentFile() will just return if logger->fileHandle
			 * is not a file.
			 */
			if(!LoggerPrimitives_SegmentFile(logger))
			{
				/* Might still want echo
				 * Commented out for now
				 * logger->loggingEnabled = false;
				 * Pointer should be set to NULL
				 */
			}
			logger->currentByteCount = 0;
		}
	}

	/* Now fetch the keyword and subkeyword.
	 * This was deferred until after testing the priority threshold for performance to not incur any overhead when no log event is needed.
	 * The C implementation actually allows NULL for these strings. 
	 * But I'm not sure if JNI supports that.
	 */
  keyword = 0;
  if (jarg3) {
    keyword = (const char*)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
  }
  // It looks like the real SWIG implementation (see LogEventNoFormat) leaks the keyword if subkeyword fails.
  subkeyword = 0;
  if (jarg4) {
    subkeyword = (const char*)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
  }




	/* Log stuff to fileHandle */
	if(logger->fileHandle != NULL)
	{
		int use_custom_print = LOGGER_USE_CUSTOM_PRINT(logger);
		
		if(0 == use_custom_print)
		{
			ret_val = LoggerPrimitives_PrintHeaderToFileHandle(logger->fileHandle,
				logger->preNewLines,
				priority, time_stamp, keyword, subkeyword);
		}
		else
		{
			ret_val = LoggerPrimitives_PrintHeaderWithCustom(logger,
				logger->preNewLines,
				priority, time_stamp, keyword, subkeyword);
		}
		if(ret_val >= 0)
		{
			logger->currentByteCount = ret_val;
			byte_counter = ret_val;
		}
		/* Try to record/preserve the first error flag because subsequent 
		 * messages might be less helpful. */
		else if(0 == error_flag)
		{
			error_flag = ret_val;
		}


		number_of_strings_in_array = (*jenv)->GetArrayLength(jenv, string_array);

		for(current_stringarray_index=0; current_stringarray_index<number_of_strings_in_array; current_stringarray_index++)
		{
			jstring current_jstring = (jstring)(*jenv)->GetObjectArrayElement(jenv, string_array, current_stringarray_index);
			const char* current_string = (const char*)(*jenv)->GetStringUTFChars(jenv, current_jstring, 0);
			// Don't forget to call `ReleaseStringUTFChars` when you're done.
			if(current_string == NULL)
			{
				if(jarg4)
				{
					(*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char*)subkeyword);
				}
				if(jarg3)
				{
					(*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char*)keyword);
				}
				LOGGERPRIMITIVES_UNLOCKMUTEX(logger);
				return -1;
			}
#if 0
			if(current_stringarray_index > 0)
			{
				/* Lua print puts tabs between comma separated parameters. Should logger do the same? */
				if(0 == use_custom_print)
				{
					ret_val = fputs("\t", logger->fileHandle);
				}
				else
				{
					ret_val = ((LoggerOpaqueData*)logger->opaqueLoggerData)->customPuts(logger, ((LoggerOpaqueData*)logger->opaqueLoggerData)->customCallbackUserData, priority, keyword, subkeyword, "\t");
				}
				if(ret_val >= 0)
				{
					/* customPuts should return the number of bytes written since it is impossible to know what it actually wrote. */
					if(0 == use_custom_print)
					{
						logger->currentByteCount += 1;
						byte_counter += 1;
					}
					else
					{
						logger->currentByteCount += ret_val;	
						byte_counter += ret_val;
					}
				}
				else if(0 == error_flag)
				{
					/* save the error condition */
					error_flag = ret_val;
				}
			}
#endif
			if(0 == use_custom_print)
			{
				ret_val = fputs(current_string, logger->fileHandle);
			}
			else
			{
				ret_val = ((LoggerOpaqueData*)logger->opaqueLoggerData)->customPuts(logger, ((LoggerOpaqueData*)logger->opaqueLoggerData)->customCallbackUserData, priority, keyword, subkeyword, current_string);
			}
			if(ret_val >= 0)
			{
				/* customPuts should return the number of bytes written since it is impossible to know what it actually wrote. */
				if(0 == use_custom_print)
				{
					logger->currentByteCount += strlen(current_string);	
					byte_counter += strlen(current_string);
				}
				else
				{
					logger->currentByteCount += ret_val;	
					byte_counter += ret_val;
				}
			}
			else if(0 == error_flag)
			{
				/* save the error condition */
				error_flag = ret_val;
			}

			(*jenv)->ReleaseStringUTFChars(jenv, current_jstring, (const char*)current_string);
			(*jenv)->DeleteLocalRef(jenv, current_jstring);
			
		}


		if(0 == use_custom_print)
		{
			ret_val = LoggerPrimitives_PrintFooterToFileHandle(logger->fileHandle,
				logger->postNewLines,
				logger->autoFlushEnabled);
		}
		else
		{
			ret_val = LoggerPrimitives_PrintFooterWithCustom(logger,
				priority, keyword, subkeyword,				
				logger->postNewLines,
				logger->autoFlushEnabled);
		}
		if(ret_val >= 0)
		{
			logger->currentByteCount += ret_val;	
			byte_counter += ret_val;			
		}
		else if(0 == error_flag)
		{
			/* save the error condition */
			error_flag = ret_val;
		}
	}




	/* Repeat again (to terminal) if echo is on. */
	/* This could have been made faster by saving the results from the previous pass into a temporary array (e.g. Lua array).
	 * But I like avoiding memory allocation/collection where necessary for other speed gains. Might be worth benchmarking some day. */
	if(logger->echoOn && (NULL != logger->echoHandle))
	{
		ret_val = LoggerPrimitives_PrintHeaderToFileHandle(logger->echoHandle,
			logger->preNewLines,
			priority, time_stamp, keyword, subkeyword);
		if((ret_val < 0) && (0 == error_flag))
		{
			error_flag = ret_val;
		}

		
		
		for(current_stringarray_index=0; current_stringarray_index<number_of_strings_in_array; current_stringarray_index++)
		{
			jstring current_jstring = (jstring)(*jenv)->GetObjectArrayElement(jenv, string_array, current_stringarray_index);
			const char* current_string = (const char*)(*jenv)->GetStringUTFChars(jenv, current_jstring, 0);
			// Don't forget to call `ReleaseStringUTFChars` when you're done.
			if(current_string == NULL)
			{
				if(jarg4)
				{
					(*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char*)subkeyword);
				}
				if(jarg3)
				{
					(*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char*)keyword);
				}
				LOGGERPRIMITIVES_UNLOCKMUTEX(logger);
				return -1;
			}
#if 0
			if(current_stringarray_index > 0)
			{
				/* Lua print puts tabs between comma separated parameters. Should logger do the same? */
				ret_val = fputs("\t", logger->echoHandle);
				if(ret_val >= 0)
				{
					/* Don't change byte count for echo */
				}
				else if(0 == error_flag)
				{
					/* save the error condition */
					error_flag = ret_val;
				}
			}
#endif
			ret_val = fputs(current_string, logger->echoHandle);
			if(ret_val >= 0)
			{
				/* Don't change byte count for echo */
			}
			else if(0 == error_flag)
			{
				/* save the error condition */
				error_flag = ret_val;
			}

			(*jenv)->ReleaseStringUTFChars(jenv, current_jstring, (const char*)current_string);
			(*jenv)->DeleteLocalRef(jenv, current_jstring);
			
		}


		ret_val = LoggerPrimitives_PrintFooterToFileHandle(logger->echoHandle,
			logger->postNewLines,
			logger->autoFlushEnabled);

		if((ret_val < 0) && (0 == error_flag))
		{
			error_flag = ret_val;
		}
	}

	LOGGERPRIMITIVES_UNLOCKMUTEX(logger);

	if(jarg4)
	{
		(*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char*)subkeyword);
	}
	if(jarg3)
	{
		(*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char*)keyword);
	}

	if(error_flag == 0)
	{
		jresult = (jint)byte_counter;
	}
	else
	{
		jresult = (jint)error_flag;
	}
  return jresult;
}



#ifdef __cplusplus
}
#endif

