//
//  HyperloopJSCoreApp.c
//  JSCoreFoundation
//
//  Created by Kota Iguchi on 11/30/13.
//  Copyright (c) 2013 Appcelerator, Inc. All rights reserved.
//

/*
 * TODO Object-oriented features such as super method call and cast
 * TODO CommonJS require keyword
 * TODO JSGlobalContext.evaluateScriptFromFile('app.js');
 */

#include "HyperloopJSCoreApp.h"

#ifdef __cplusplus
extern "C" {
#endif

static JavaVM* jvm = NULL;
static jclass  jniMethodInvokerClass = NULL;
static jobject jniMethodInvokerObj   = NULL;

bool JS_registerClass(JSGlobalContextRef context, JSObjectRef parentObject,
                      const char* className, JSClassDefinition* definition)
{
    JSStringRef js_className = JSStringCreateWithUTF8CString(className);
    JSObjectRef classObject = JSObjectMake(context, JSClassCreate(definition), NULL);
    JSObjectSetProperty(context, parentObject,
                        js_className, classObject,
                        kJSPropertyAttributeNone, NULL);
    JSStringRelease(js_className);
    return true;
}

bool JS_registerNamespace(JSGlobalContextRef context, JSObjectRef namespaceObj,
                          JSObjectRef parentNamespace, const char* name)
{
    JSStringRef js_name = JSStringCreateWithUTF8CString(name);
    JSObjectSetProperty(context, parentNamespace,
                        js_name, namespaceObj,
                        kJSPropertyAttributeNone, NULL);
    JSStringRelease(js_name);
    
    return true;
}

bool JS_registerFunction(JSGlobalContextRef context, JSObjectRef object,
                         const char* functionName, JSObjectCallAsFunctionCallback callback)
{
    JSStringRef js_functionName = JSStringCreateWithUTF8CString(functionName);
    JSObjectSetProperty(context, object, js_functionName,
                        JSObjectMakeFunctionWithCallback(context, js_functionName, callback), 
                        kJSPropertyAttributeNone, NULL);
    JSStringRelease(js_functionName);
    return true;
}

JSValueRef _wrap_console_debug(JSContextRef context, JSObjectRef function,
                               JSObjectRef thisObject, size_t argc, const JSValueRef argv[], JSValueRef* exception)
{
    CONSOLE_LOG_FROM_ARG(0, arg0, LOGD)
}
JSValueRef _wrap_console_info(JSContextRef context, JSObjectRef function,
                               JSObjectRef thisObject, size_t argc, const JSValueRef argv[], JSValueRef* exception)
{
    CONSOLE_LOG_FROM_ARG(0, arg0, LOGI)
}
JSValueRef _wrap_console_warn(JSContextRef context, JSObjectRef function,
                               JSObjectRef thisObject, size_t argc, const JSValueRef argv[], JSValueRef* exception)
{
    CONSOLE_LOG_FROM_ARG(0, arg0, LOGW)
}
JSValueRef _wrap_console_error(JSContextRef context, JSObjectRef function,
                               JSObjectRef thisObject, size_t argc, const JSValueRef argv[], JSValueRef* exception)
{
    CONSOLE_LOG_FROM_ARG(0, arg0, LOGE)
}
JSValueRef _wrap_console_log(JSContextRef context, JSObjectRef function,
                               JSObjectRef thisObject, size_t argc, const JSValueRef argv[], JSValueRef* exception)
{
    CONSOLE_LOG_FROM_ARG(0, arg0, LOGI)
}
    
JSStaticValue _BaseObject_values[] =
{
    {0, 0, 0, 0}
};

JSStaticFunction _BaseObject_functions[] =
{
    {0, 0, 0}
};
JSClassDefinition _BaseObject_objectDefinition;
JSClassRef _BaseObject_classRef;

JSStaticValue     namespace_values[] = {{0, 0, 0, 0}};
JSStaticFunction  namespace_functions[] = {{0, 0, 0}};
JSClassDefinition namespace_classDefinition;
    
JSStaticValue     console_values[] = {{0, 0, 0, 0}};
JSStaticFunction  console_functions[] =
{
    { "debug", _wrap_console_debug, kJSPropertyAttributeNone },
    { "info",  _wrap_console_info,  kJSPropertyAttributeNone },
    { "warn",  _wrap_console_warn,  kJSPropertyAttributeNone },
    { "error", _wrap_console_error, kJSPropertyAttributeNone },
    { "log",   _wrap_console_log,   kJSPropertyAttributeNone },
    {0, 0, 0}
};
JSClassDefinition console_classDefinition;

void _wrap_delete_JObject(JSObjectRef thisObject) {
    Hyperloop_JSObjectPrivateData* prv = (Hyperloop_JSObjectPrivateData*)JSObjectGetPrivate(thisObject);
    JNI_ENV_ENTER
    if (prv && prv->object)
    {
        (*env)->DeleteGlobalRef(env, prv->object);
    }
    JNI_ENV_EXIT
    free(prv);
}
/************************************************************/
/** JNI METHODS ID GENERATED BY HYPERLOOP COMPILER - START **/
/************************************************************/

jmethodID jmethodId_JNIMethodInvoker_CallVoidMethod0 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallVoidMethod1 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallVoidMethod2 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallObjectMethod0 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallStringMethod0 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallBooleanMethod0 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallCharMethod0 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallShortMethod0 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallIntMethod0 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallLongMethod0 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallFloatMethod0 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallDoubleMethod0 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallObject0 = NULL;
jmethodID jmethodId_JNIMethodInvoker_CallObject1 = NULL;

/*
 * java.util.Date
 */

JSClassDefinition _java_util_Date_classDefinition;
JSClassDefinition _java_util_Date_objectDefinition;
JSClassRef _java_util_Date_classRef;
    
/* new java.util.Date() */
int methodId_M2147483648 = -2147483648;
JSObjectRef _wrap_new_java_util_Date(JSContextRef context, JSObjectRef thisObject,
                             size_t argc, const JSValueRef argv[], JSValueRef* exception)
{
    JNI_ENV_ENTER
    jobject obj = (*env)->CallObjectMethod(env, jniMethodInvokerObj,
                                           jmethodId_JNIMethodInvoker_CallObject0,
                                           methodId_M2147483648);
    Hyperloop_JSObjectPrivateData* prv = (Hyperloop_JSObjectPrivateData*)malloc(sizeof(Hyperloop_JSObjectPrivateData));
    prv->object = (*env)->NewGlobalRef(env, obj);
    JNI_ENV_EXIT
    return JSObjectMake(context, _java_util_Date_classRef, prv);
}

/* java.util.Date#getTime() */
int methodId_M2147483647 = -2147483647;
JSValueRef _wrap_java_util_Date_getTime_M2147483647(
    JSContextRef context, JSObjectRef function, JSObjectRef thisObject,
    size_t argc, const JSValueRef argv[], JSValueRef* exception)
{
    Hyperloop_JSObjectPrivateData* prv = (Hyperloop_JSObjectPrivateData*)JSObjectGetPrivate(thisObject);
    JNI_ENV_ENTER
    jlong value = (*env)->CallLongMethod(env, jniMethodInvokerObj,
            jmethodId_JNIMethodInvoker_CallLongMethod0,
            methodId_M2147483647, prv->object);
    JNI_ENV_EXIT
    
    return JSValueMakeNumber(context, value);
}

/* java.util.Date#toString() */
int methodId_M2147483646 = -2147483646;
JSValueRef _wrap_java_util_Date_toString_M2147483646(
    JSContextRef context, JSObjectRef function, JSObjectRef thisObject,
    size_t argc, const JSValueRef argv[], JSValueRef* exception)
{
    Hyperloop_JSObjectPrivateData* prv = (Hyperloop_JSObjectPrivateData*)JSObjectGetPrivate(thisObject);
    JNI_ENV_ENTER
    jstring value = (*env)->CallObjectMethod(env, jniMethodInvokerObj,
            jmethodId_JNIMethodInvoker_CallObjectMethod0,
            methodId_M2147483646, prv->object);
    JSSTRINGREF_FROM_JSTRING(value, jvalue);
    JNI_ENV_EXIT

    // toString() returns JS string so that not to change the default behavior of JS Object.
    // do we have to make a special method which returns java.lang.String object?
    return JSValueMakeString(context, jvalue);
}

JSStaticValue     _java_util_Date_staticValues[] = {{0, 0, 0, 0}};
JSStaticFunction  _java_util_Date_staticFunctions[] = {{0, 0, 0}};
JSStaticValue     _java_util_Date_values[] = {{0, 0, 0, 0}};
JSStaticFunction  _java_util_Date_functions[] =
{
    {"getTime", _wrap_java_util_Date_getTime_M2147483647, kJSPropertyAttributeNone},
    {"toString", _wrap_java_util_Date_toString_M2147483646, kJSPropertyAttributeNone},
    {0, 0, 0}
};

/*
 * java.io.FileNotFoundException
 */
JSClassDefinition _java_io_FileNotFoundException_classDefinition;
JSClassDefinition _java_io_FileNotFoundException_objectDefinition;
JSClassRef _java_io_FileNotFoundException_classRef;
JSStaticValue     _java_io_FileNotFoundException_staticValues[] = {{0, 0, 0, 0}};
JSStaticFunction  _java_io_FileNotFoundException_staticFunctions[] = {{0, 0, 0}};
JSStaticValue     _java_io_FileNotFoundException_values[] = {{0, 0, 0, 0}};
JSStaticFunction  _java_io_FileNotFoundException_functions[] ={{0, 0, 0}};
    
/* new java.io.FileNotFoundException() */
int methodId_M2147483642 = -2147483642;
JSObjectRef _wrap_new_java_io_FileNotFoundException(JSContextRef context, JSObjectRef thisObject,
                             size_t argc, const JSValueRef argv[], JSValueRef* exception)
{
    JNI_ENV_ENTER
    jobject obj = (*env)->CallObjectMethod(env, jniMethodInvokerObj,
                                           jmethodId_JNIMethodInvoker_CallObject0,
                                           methodId_M2147483642);
    Hyperloop_JSObjectPrivateData* prv = (Hyperloop_JSObjectPrivateData*)malloc(sizeof(Hyperloop_JSObjectPrivateData));
    prv->object = (*env)->NewGlobalRef(env, obj);
    JNI_ENV_EXIT
    return JSObjectMake(context, _java_io_FileNotFoundException_classRef, prv);
}

/*
 * java.io.PrintStream
 */
JSClassDefinition _java_io_PrintStream_classDefinition;
JSClassDefinition _java_io_PrintStream_objectDefinition;
JSClassRef _java_io_PrintStream_classRef;
int methodId_M2147483644 = -2147483644;
JSObjectRef _wrap_new_java_io_PrintStream(JSContextRef context, JSObjectRef thisObject,
                             size_t argc, const JSValueRef argv[], JSValueRef* exception)
{
    JNI_ENV_ENTER
    JSTRING_FROM_ARG(0, jstring0)
    jobject obj = (*env)->CallObjectMethod(env, jniMethodInvokerObj,
                                           jmethodId_JNIMethodInvoker_CallObject1,
                                           methodId_M2147483644, jstring0);
    JSObjectRef retObj;
    if ((*env)->ExceptionCheck(env) == JNI_TRUE)
    {
        jthrowable exceptionObj = (*env)->ExceptionOccurred(env);
        Hyperloop_JSObjectPrivateData* prv = (Hyperloop_JSObjectPrivateData*)malloc(sizeof(Hyperloop_JSObjectPrivateData));
        prv->object = (*env)->NewGlobalRef(env, exceptionObj);
        *exception = JSObjectMake(context, _java_io_FileNotFoundException_classRef, prv);
        retObj = NULL;
    } else {
        Hyperloop_JSObjectPrivateData* prv = (Hyperloop_JSObjectPrivateData*)malloc(sizeof(Hyperloop_JSObjectPrivateData));
        prv->object = (*env)->NewGlobalRef(env, obj);
        retObj = JSObjectMake(context, _java_io_PrintStream_classRef, prv);
    }
    JNI_ENV_EXIT
    return retObj;
}

/* java.io.PrintStream#println */
int methodId_M2147483643 = -2147483643;
JSValueRef _wrap_java_io_PrintStream_println_M2147483643(
    JSContextRef context, JSObjectRef function, JSObjectRef thisObject,
    size_t argc, const JSValueRef argv[], JSValueRef* exception)
{
    Hyperloop_JSObjectPrivateData* prv = (Hyperloop_JSObjectPrivateData*)JSObjectGetPrivate(thisObject);
    JNI_ENV_ENTER
    JSTRING_FROM_ARG(0, jstring0)
    (*env)->CallVoidMethod(env, jniMethodInvokerObj,
            jmethodId_JNIMethodInvoker_CallVoidMethod1,
            methodId_M2147483643, prv->object, jstring0);
    JNI_ENV_EXIT
    
    return JSValueMakeUndefined(context);
}

JSStaticValue     _java_io_PrintStream_staticValues[] = {{0, 0, 0, 0}};
JSStaticFunction  _java_io_PrintStream_staticFunctions[] = {{0, 0, 0}};
JSStaticValue     _java_io_PrintStream_values[] = {{0, 0, 0, 0}};
JSStaticFunction  _java_io_PrintStream_functions[] =
{
    { "println", _wrap_java_io_PrintStream_println_M2147483643, kJSPropertyAttributeNone },
    {0, 0, 0}
};
    
/*
 * java.lang.System
 */
    
/* java.lang.System.out */
int methodId_M2147483645 = -2147483645;
JSValueRef _wrap_java_lang_System_out_get(
                JSContextRef context, JSObjectRef thisObject,
                JSStringRef propertyName, JSValueRef* exception)
{
    JNI_ENV_ENTER
    jobject obj = (*env)->CallObjectMethod(env, jniMethodInvokerObj,
                                           jmethodId_JNIMethodInvoker_CallObject0,
                                           methodId_M2147483645);
    Hyperloop_JSObjectPrivateData* prv = (Hyperloop_JSObjectPrivateData*)malloc(sizeof(Hyperloop_JSObjectPrivateData));
    prv->object = (*env)->NewGlobalRef(env, obj);
    
    JNI_ENV_EXIT
    return JSObjectMake(context, _java_io_PrintStream_classRef, prv);
}
bool _wrap_java_lang_System_out_set(
                JSContextRef context, JSObjectRef thisObject,
                JSStringRef propertyName, JSValueRef value, JSValueRef* exception)
{
    return false;
}

JSStaticValue _java_lang_System_values[] =
{
    {
        "out", _wrap_java_lang_System_out_get, _wrap_java_lang_System_out_set, kJSPropertyAttributeNone
    },
    {0, 0, 0, 0}
};
JSStaticFunction _java_lang_System_functions[] =
{
    {0, 0, 0}
};
JSClassDefinition _java_lang_System_classDefinition;

/*
 * Cache JNI invoker method id so that we can call it faster.
 */
bool JSCoreApp_CacheInvokerMethods(JNIEnv* env) {
    jmethodId_JNIMethodInvoker_CallVoidMethod0 = (*env)->GetMethodID(env,
        jniMethodInvokerClass, "CallVoidMethod0", "(ILjava/lang/Object;)V");
    jmethodId_JNIMethodInvoker_CallVoidMethod1 = (*env)->GetMethodID(env,
        jniMethodInvokerClass, "CallVoidMethod1", "(ILjava/lang/Object;Ljava/lang/Object;)V");
    jmethodId_JNIMethodInvoker_CallVoidMethod2 = (*env)->GetMethodID(env,
        jniMethodInvokerClass, "CallVoidMethod2", "(ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V");
    jmethodId_JNIMethodInvoker_CallLongMethod0 = (*env)->GetMethodID(env,
        jniMethodInvokerClass, "CallLongMethod0", "(ILjava/lang/Object;)J");
    jmethodId_JNIMethodInvoker_CallObjectMethod0 = (*env)->GetMethodID(env,
        jniMethodInvokerClass, "CallObjectMethod0", "(ILjava/lang/Object;)Ljava/lang/Object;");
    
    jmethodId_JNIMethodInvoker_CallObject0 = (*env)->GetMethodID(env,
        jniMethodInvokerClass, "CallObject0", "(I)Ljava/lang/Object;");
    jmethodId_JNIMethodInvoker_CallObject1 = (*env)->GetMethodID(env,
        jniMethodInvokerClass, "CallObject1", "(ILjava/lang/Object;)Ljava/lang/Object;");

    return true;
}

bool JSCoreApp_RegisterJSClasses(JSGlobalContextRef context, JSObjectRef global_object) {
    
    /* Initialize the base object */
    
    _BaseObject_objectDefinition.staticFunctions = _BaseObject_functions;
    _BaseObject_objectDefinition.staticValues = _BaseObject_values;
    _BaseObject_classRef = JSClassCreate(&_BaseObject_objectDefinition);
    
    /* Create object for 'console' */
    
    console_classDefinition.staticFunctions = console_functions;
    console_classDefinition.staticValues = console_values;
    JSObjectRef console_object = JSObjectMake(context, JSClassCreate(&console_classDefinition), NULL);
    JS_registerNamespace(context, console_object, global_object, "console");

    /* Create objects for namespaces */
    
    namespace_classDefinition.staticFunctions = namespace_functions;
    namespace_classDefinition.staticValues = namespace_values;
    
    /* java */
    JSObjectRef java_object = JSObjectMake(context, JSClassCreate(&namespace_classDefinition), NULL);
    JS_registerNamespace(context, java_object, global_object, "java");
    
    /* java.lang */
    JSObjectRef java_lang_object = JSObjectMake(context, JSClassCreate(&namespace_classDefinition), NULL);
    JS_registerNamespace(context, java_lang_object, java_object, "lang");
    
    /* java.util */
    JSObjectRef java_util_object = JSObjectMake(context, JSClassCreate(&namespace_classDefinition), NULL);
    JS_registerNamespace(context, java_util_object, java_object, "util");
    
    /* java.io */
    JSObjectRef java_io_object = JSObjectMake(context, JSClassCreate(&namespace_classDefinition), NULL);
    JS_registerNamespace(context, java_io_object, java_object, "io");
    
    /* Register classes */

    /* java.lang.System */
    _java_lang_System_classDefinition.staticFunctions = _java_lang_System_functions;
    _java_lang_System_classDefinition.staticValues = _java_lang_System_values;
    JSObjectRef _java_lang_System_object = JSObjectMake(context, JSClassCreate(&_java_lang_System_classDefinition), NULL);
    JS_registerNamespace(context, _java_lang_System_object, java_lang_object, "System");

    /* java.io.FileNotFoundException */
    _java_io_FileNotFoundException_classDefinition.staticFunctions = _java_io_FileNotFoundException_staticFunctions;
    _java_io_FileNotFoundException_classDefinition.staticValues = _java_io_FileNotFoundException_staticValues;
    _java_io_FileNotFoundException_classDefinition.callAsConstructor = _wrap_new_java_io_FileNotFoundException;
    _java_io_FileNotFoundException_classDefinition.finalize = _wrap_delete_JObject;
    _java_io_FileNotFoundException_objectDefinition.staticValues = _java_io_FileNotFoundException_values;
    _java_io_FileNotFoundException_objectDefinition.staticFunctions = _java_io_FileNotFoundException_functions;
    _java_io_FileNotFoundException_objectDefinition.parentClass = _BaseObject_classRef;
    _java_io_FileNotFoundException_classRef = JSClassCreate(&_java_io_FileNotFoundException_objectDefinition);
    
    JS_registerClass(context, java_io_object, "FileNotFoundException", &_java_io_FileNotFoundException_classDefinition);
    
    /* java.io.PrintStream */
    _java_io_PrintStream_classDefinition.staticFunctions = _java_io_PrintStream_staticFunctions;
    _java_io_PrintStream_classDefinition.staticValues = _java_io_PrintStream_staticValues;
    _java_io_PrintStream_classDefinition.callAsConstructor = _wrap_new_java_io_PrintStream;
    _java_io_PrintStream_classDefinition.finalize = _wrap_delete_JObject;
    _java_io_PrintStream_objectDefinition.staticValues = _java_io_PrintStream_values;
    _java_io_PrintStream_objectDefinition.staticFunctions = _java_io_PrintStream_functions;
    _java_io_PrintStream_objectDefinition.parentClass = _BaseObject_classRef;
    _java_io_PrintStream_classRef = JSClassCreate(&_java_io_PrintStream_objectDefinition);
    
    JS_registerClass(context, java_io_object, "PrintStream", &_java_io_PrintStream_classDefinition);
    
    /* java.util.Date */
    _java_util_Date_classDefinition.staticFunctions = _java_util_Date_staticFunctions;
    _java_util_Date_classDefinition.staticValues = _java_util_Date_staticValues;
    _java_util_Date_classDefinition.callAsConstructor = _wrap_new_java_util_Date;
    _java_util_Date_classDefinition.finalize = _wrap_delete_JObject;
    _java_util_Date_objectDefinition.staticValues = _java_util_Date_values;
    _java_util_Date_objectDefinition.staticFunctions = _java_util_Date_functions;
    _java_util_Date_objectDefinition.parentClass = _BaseObject_classRef;
    _java_util_Date_classRef = JSClassCreate(&_java_util_Date_objectDefinition);
    
    JS_registerClass(context, java_util_object, "Date", &_java_util_Date_classDefinition);
    
    return true;
}

/*******************************************************/
/** JNI METHODS GENERATED BY HYPERLOOP COMPILER - END **/
/*******************************************************/

bool JSCoreApp_Load(JavaVM* vm, JNIEnv* env, jclass invokerClass, jobject invokerObj,
                    JSGlobalContextRef context, JSObjectRef global_object)
{
    jvm = vm;
    jniMethodInvokerClass = invokerClass;
    jniMethodInvokerObj   = invokerObj;
    
    JSCoreApp_CacheInvokerMethods(env);
    JSCoreApp_RegisterJSClasses(context, global_object);
    
    return true;
}    

#ifdef __cplusplus
}
#endif
