        FIND_LIBRARY( ANDROID_LOG_LIBRARY log )
		FIND_LIBRARY( ANDROID_CPPSTD_LIBRARY stdc++ )
		#        FIND_LIBRARY( ANDROID_ANDROID_LIBRARY android )

list(APPEND JavaScriptCore_LIBRARIES
    ${ANDROID_LOG_LIBRARY}
	${ANDROID_CPPSTD_LIBRARY}

	#    ${ANDROID_ANDROID_LIBRARY}
)

